import 'package:first_movie_app/models/movie.dart';

final movies = [
  Movie(id: 1, name: "Blackmail", category: "Thriller", releaseYear: 1929, rating: 7.0, description: "Alice White is the daughter of a shopkeeper in 1920s London. Her boyfriend, Frank Webber is a Scotland Yard detective who seems more interested in police work than in her. Frank takes Alice out one night, but she has secretly arranged to meet another man. Later that night, Alice agrees to go back to his flat to see his studio. The man has other ideas, and as he tries to rape Alice, she defends herself and kills him with a bread knife. When the body is discovered, Frank is assigned to the case, he quickly determines that Alice is the killer, but so has someone else, and blackmail is threatened", image: "images/blackmail.jpg"),
  Movie(id: 2, name: "Psycho", category: "Thriller", releaseYear: 1960, rating: 8.5, description: "Phoenix office worker Marion Crane is fed up with the way life has treated her. She has to meet her lover Sam in lunch breaks, and they cannot get married because Sam has to give most of his money away in alimony. One Friday, Marion is trusted to bank forty thousand dollars by her employer. Seeing the opportunity to take the money and start a new life, Marion leaves town and heads towards Sam's California store. Tired after the long drive and caught in a storm, she gets off the main highway and pulls into the Bates Motel. The motel is managed by a quiet young man called Norman who seems to be dominated by his mother. ", image: "images/psycho.jpg"),
  Movie(id: 3, name: "The Birds", category: "Thriller", releaseYear: 1963, rating: 7.7, description: "Melanie Daniels is the modern rich socialite, part of the jet-set who always gets what she wants. When lawyer Mitch Brenner sees her in a pet shop, he plays something of a practical joke on her, and she decides to return the favor. She drives about an hour north of San Francisco to Bodega Bay, where Mitch spends the weekends with his mother Lydia and younger sister Cathy. Soon after her arrival, however, the birds in the area begin to act strangely. A seagull attacks Melanie as she is crossing the bay in a small boat, and then, Lydia finds her neighbor dead, obviously the victim of a bird attack. Soon, birds in the hundreds and thousands are attacking anyone they find out of doors. There is no explanation as to why this might be happening, and as the birds continue their vicious attacks, survival becomes the priority.", image: "images/the_birds.jpg"),
  Movie(id: 4, name: "Vertigo", category: "Thriller", releaseYear: 1958, rating: 8.3, description: "Following his early retirement as a detective from the San Francisco Police Department, John Ferguson - Scottie to his friends - becomes obsessed with two women in succession, those obsessions which trouble his long time friend and former fiancée, Midge Wood, a designer of women's undergarments. The first is wealthy and elegant platinum blonde Madeleine Elster, the wife of his college acquaintance Gavin Elster, who hires John to follow her in Gavin's belief that she may be a danger to herself in thinking that she has recently been possessed by the spirit of Carlotta Valdes, Madeleine's great-grandmother who she knows nothing about, but who Gavin knows committed suicide in being mentally unbalanced when she was twenty-six, Madeleine's current age. The second is Judy Barton, who John spots on the street one day. Judy is a working class girl, but what makes John obsessed with her is that, despite her working class style and her brunette hair, she is the spitting image of Madeleine, into who he tries to transform Judy. The initial question that John has is if there is some connection between Madeleine and Judy. What happens between John and individually with Madeleine and Judy is affected by the reason John took that early retirement: a recent workplace incident that showed that he is acrophobic which leads to a severe case of vertigo whenever he looks down from tall heights.", image: "images/vertigo.jpg"),
  Movie(id: 5, name: "Rear Window", category: "Thriller", releaseYear: 1954, rating: 8.5, description: "Professional photographer L.B. 'Jeff' Jefferies breaks his leg while getting an action shot at an auto race. Confined to his New York apartment, he spends his time looking out of the rear window observing the neighbors. He begins to suspect that a man across the courtyard may have murdered his wife. Jeff enlists the help of his high society fashion-consultant girlfriend Lisa Fremont and his visiting nurse Stella to investigate.", image: "images/rear_window.jpg"),
  Movie(id: 6, name: "North by Northwest", category: "Thriller", releaseYear: 1959, rating: 8.3, description: "Madison Avenue advertising man Roger Thornhill finds himself thrust into the world of spies when he is mistaken for a man by the name of George Kaplan. Foreign spy Philip Vandamm and his henchman Leonard try to eliminate him but when Thornhill tries to make sense of the case, he is framed for murder. Now on the run from the police, he manages to board the 20th Century Limited bound for Chicago where he meets a beautiful blond, Eve Kendall, who helps him to evade the authorities. His world is turned upside down yet again when he learns that Eve isn't the innocent bystander he thought she was. Not all is as it seems however, leading to a dramatic rescue and escape at the top of Mt. Rushmore. ", image: "images/north_by_northwest.jpg"),
  Movie(id: 7, name: "When Boy Leaves Home", category: "Thriller", releaseYear: 1927, rating: 6.1, description: "Public schoolboy Roddy Berwick is expelled from school when he takes the blame for a friend's charge and his life falls apart in a series of misadventures.", image: "images/when_boy_leaves_home.jpg"),
  Movie(id: 8, name: "The Farmer's Wife", category: "Thriller", releaseYear: 1928, rating: 5.9, description: "After his daughter weds, a middle-aged widower with a profitable farm decides to remarry, but finds choosing a suitable mate a problematic process.", image: "images/the_farmers_wife.jpg"),
  Movie(id: 9, name: "Rebecca", category: "Thriller", releaseYear: 1940, rating: 8.1, description: "A self-conscious woman juggles adjusting to her new role as an aristocrat's wife and avoiding being intimidated by his first wife's spectral presence.", image: "images/rebecca.jpeg"),
];